# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: One sentence introducing yourself or what you do

# Social icons
facebook: monmoranshi
linkedin: username
github: nonark
deviantart: username
codepen: username

footer: Â© Taken theme

# Build settings
encoding: "utf-8"
markdown: kramdown